BOARD_TAG = diecimila
#BOARD_TAG = uno
ARDUINO_LIBS = Wire BasicTerm Ultrasonic/Ultrasonic Troyka-IMU
USER_LIB_PATH = ../Libraries
ISP_PROG = dragon_isp
ISP_PORT = usb

include /usr/share/arduino/Arduino.mk
